export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER_BY_ID = 'FETCH_USER_BY_ID';
export const UPDATE_USER_BY_ID = 'UPDATE_USER_BY_ID';
export const DELETE_USER_BY_ID = 'DELETE_USER_BY_ID';
