const RouteNames = {
  forgetPassword: '/forget-password',
  signup: '/signup',
  login: '/',
  home: '/home',
  resetPassword: '/reset-password',
  profile: '/profile',
  dashboard: '/dashboard',
  orderHistory: '/orderHistory',
  addOrderHistory: '/orderHistory/add',
  editOrderHistory: '/orderHistory/edit',
  users: '/users',
  editUser: '/users/edit',
  addUser: '/users/add',
  vendors: '/vendors',
  editVendor: '/vendors/edit',
  addVendor: '/vendors/add',
  categories: '/categories',
  addCategory: '/categories/add',
  editCategory: '/categories/edit',
  menu: '/menu',
  restraunt: '/restraunt',
  addMenu: '/addmenu',
  orderhistory: '/orderhistory',
  orderlist: '/orderlist',
  categorylist: '/categorylist',
  addcategory: '/addcategory',
  editMenu: '/editmenu',
};

export default RouteNames;
