const RouteNames = {
  forgetPassword: '/forget-password',
  signup: '/signup',
  login: '/',
  home: '/home',
  resetPassword: '/reset-password',
  profile: '/profile',
  dashboard: '/dashboard',
  addVendor: '/addvendor',
  vendors: '/vendors',
  editVendor: '/editvendor',
  users: '/users',
  orderHistory: '/orderhistory',
  categories: '/categories',
  addUser: '/adduser',
  editUser: '/edituser',
  editOrderHistory: '/editorderhistory',
  addHistory: '/addHistory',
  addCategory: '/addcategory',
  editCategory: '/editcategory',
  menu: '/menu',
  restraunt: '/restraunt',
  addMenu: '/addmenu',
  orderhistory: '/orderhistory',
  orderlist: '/orderlist',
  categorylist: '/categorylist',
  addcategory: '/addcategory',
  editMenu: '/editmenu',
};

export default RouteNames;
