const RouteNames = {
  forgetPassword: '/forget-password',
  signup: '/signup',
  login: '/login',
  home: '/home',
  resetPassword: '/reset-password',
  profile: '/profile',
  dashboard: '/dashboard',
  orderhistory: '/orderhistory',
  vendorcategorylist: '/categorylist',
  vendors: '/vendors',
  usersList: '/userslist',
  categoryList: '/category-list',
  orderHistory: '/orderHistory',
  addOrderHistory: '/orderHistory/add',
  editOrderHistory: '/orderHistory/edit',
  users: '/users',
  editUser: '/users/edit',
  addUser: '/users/add',
  editVendor: '/vendors/edit',
  addVendor: '/vendors/add',
  categories: '/categories',
  addCategory: '/categories/add',
  editCategory: '/categories/edit',
  restaurant: '/restaurant',
  menuList: '/menu',
};

export default RouteNames;
