export const FETCH_VENDORS = 'FETCH_VENDORS';
export const FETCH_VENDOR_BY_ID = 'FETCH_VENDOR_BY_ID';
export const UPDATE_VENDOR_BY_ID = 'FETCH_VENDOR_BY_ID';
export const DELETE_VENDOR_BY_ID = 'FETCH_VENDOR_BY_ID';
